const ACTIVITEITEN_DATA = [
  {
    "id": "dl-voortgangsrapportage-2026-12",
    "titel": "Opleverdatum voortgangsrapportage",
    "datum": "2026-12-01",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "deadline",
    "beschrijving": "Document met voortgangsrapportage, situatie-analyse en plan van aanpak per organisatie met eigen transformatieaanjager",
    "doelgroep": "Transformatieaanjagers",
    "actielijn": "Algemeen",
    "url": null,
    "relatie": null,
    "contactpersoon": "denise.seelen@tpz-midden.nl"
  },
  {
    "id": "dl-voortgangsrapportage-2027-06",
    "titel": "Opleverdatum voortgangsrapportage",
    "datum": "2027-06-01",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "deadline",
    "beschrijving": "Document met voortgangsrapportage, situatie-analyse en plan van aanpak per organisatie met eigen transformatieaanjager",
    "doelgroep": "Transformatieaanjagers",
    "actielijn": "Algemeen",
    "url": null,
    "relatie": null,
    "contactpersoon": "denise.seelen@tpz-midden.nl"
  },
  {
    "id": "dl-evaluatie-2027-12",
    "titel": "Opleverdatum voortgangsrapportage",
    "datum": "2027-12-01",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "deadline",
    "beschrijving": "Document met evaluatie per organisatie waar een implementatie projectleider actief is met daarin  de voortgangsrapportage, situatie-analyse en borgingsplan per organisatie",
    "doelgroep": "Transformatieaanjagers",
    "actielijn": "Algemeen",
    "url": null,
    "relatie": null,
    "contactpersoon": "denise.seelen@tpz-midden.nl"
  },
  {
    "id": "dl-financiele-rapportage-2026-08",
    "titel": "Financiële rapportage januari t/m juni 2026",
    "datum": "2026-08-07",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "deadline",
    "beschrijving": "Halfjaarlijkse rapportage",
    "doelgroep": "Projectcontrollers",
    "actielijn": "Algemeen",
    "url": null,
    "relatie": null,
    "contactpersoon": "A.M.vanderLinden-Gruntjes@umcutrecht.nl"
  },
  {
    "id": "dl-financiele-rapportage-2027-02",
    "titel": "Financiële rapportage juli t/m december 2026",
    "datum": "2027-02-05",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "deadline",
    "beschrijving": "Halfjaarlijkse rapportage",
    "doelgroep": "Projectcontrollers",
    "actielijn": "Algemeen",
    "url": null,
    "relatie": null,
    "contactpersoon": "A.M.vanderLinden-Gruntjes@umcutrecht.nl"
  },
  {
    "id": "dl-financiele-rapportage-2027-08",
    "titel": "Financiële rapportage januari t/m juni 2027",
    "datum": "2027-08-06",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "deadline",
    "beschrijving": "Halfjaarlijkse rapportage",
    "doelgroep": "Projectcontrollers",
    "actielijn": "Algemeen",
    "url": null,
    "relatie": null,
    "contactpersoon": "A.M.vanderLinden-Gruntjes@umcutrecht.nl"
  },
  {
    "id": "Ie-kppNjQUG2Y2l6imsdkZgAEQy_",
    "titel": "Webinar ‘Praten over morgen: proactieve zorgplanning bij COPD’ (doelgroep: verpleegkundigen)",
    "datum": "2026-05-12",
    "einddatum": null,
    "tijd": null,
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Webinar ‘Praten over morgen: proactieve zorgplanning bij COPD’ Samen met V&VN longverpleegkundigen organiseert NPPZII een webinar voor verpleegkundigen. Sprekers zijn Olaf Geerse, longarts i.o. en Linda Brandjes, VS. Mensen met vergevorderd COPD krijgen minder vaak palliatieve zorg aangeboden dat bijv. mensen met kanker. Toch is COPD een ongeneeslijke ziekte die veel klachten met zich meebrengt. Het gesprek aangaan bij deze patiënten en hun naasten is belangrijk. Er zijn nog plekken vrij. Geef j...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": null,
    "relatie": "direct"
  },
  {
    "id": "wjkGji2AIE2Wtfs3LYbr1ZgAGLld",
    "titel": "Workshop 'Praten over later - het goede gesprek op het juist moment' (voor huisartsen en POHs)",
    "datum": "2026-05-27",
    "einddatum": null,
    "tijd": "18:00 - 20:00",
    "locatie": null,
    "type": "werkgroep",
    "beschrijving": "👥 𝗣𝗿𝗮𝘁𝗲𝗻 𝗼𝘃𝗲𝗿 𝗹𝗮𝘁𝗲𝗿 – 𝗵𝗲𝘁 𝗴𝗼𝗲𝗱𝗲 𝗴𝗲𝘀𝗽𝗿𝗲𝗸 𝗼𝗽 𝗵𝗲𝘁 𝗷𝘂𝗶𝘀𝘁𝗲 𝗺𝗼𝗺𝗲𝗻𝘁 𝘞𝘢𝘯𝘯𝘦𝘦𝘳 𝘣𝘦𝘷𝘪𝘯𝘥𝘵 𝘦𝘦𝘯 𝘱𝘢𝘵𝘪ë𝘯𝘵 𝘻𝘪𝘤𝘩 𝘦𝘤𝘩𝘵 𝘪𝘯 𝘥𝘦 𝘱𝘢𝘭𝘭𝘪𝘢𝘵𝘪𝘦𝘷𝘦 𝘧𝘢𝘴𝘦? 𝘞𝘢𝘯𝘯𝘦𝘦𝘳 𝘣𝘦𝘨𝘪𝘯 𝘫𝘦 𝘩𝘦𝘵 𝘨𝘦𝘴𝘱𝘳𝘦𝘬 𝘰𝘷𝘦𝘳 ‘𝘭𝘢𝘵𝘦𝘳’? In de drukte van alledag komt proactieve zorgplanning (PZP) vaak pas op gang als de tijd eigenlijk al dringt. Herkenbaar voor jou? 📅 Op 𝘄𝗼𝗲𝗻𝘀𝗱𝗮𝗴 𝟮𝟳 𝗺𝗲𝗶 organiseren we de interactieve worksh...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://www.linkedin.com/posts/unicumhuisartsenzorg_poh-huisarts-scholing-activity-7452310177443164160-of4R?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAP9N9sBdJ8SSmZT990KVtTkDvdBuNGgL5Q",
    "relatie": "direct"
  },
  {
    "id": "4SdeNQvWSEuwycIAmEHToZgAHv-3",
    "titel": "Scholing Stervensfase (voor verzorgenden en helpenden werkzaam in een verpleeghuis)",
    "datum": "2026-06-09",
    "einddatum": null,
    "tijd": "16:30 - 19:00",
    "locatie": null,
    "type": "bijeenkomst",
    "beschrijving": "Deze scholing richt zich op het bieden van zorg in de stervensfase, de lichamelijke kenmerken van iemand die sterft, de begeleiding van naasten hierbij en wat je kunt doen om goed samen te werken met je collega's rond het sterfbed van een bewoner. Onderwerpen die tijdens de scholing aan bod komen zijn onder andere: Hoe herken je de stervensfase en welke symptomen horen bij een 'normaal' sterfproces? Welke symptomen zijn belangrijk om iets mee te doen omdat deze niet bij het normale sterven horen...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://palliaweb.nl/netwerk-utrechtstadenzuidoost/hulpverleners/scholing/scholing-stervensfase",
    "relatie": "niet-direct"
  },
  {
    "id": "hdbdc8Ic2UWT6g8sWruNipgAECUD",
    "titel": "Online inspiratiesessie 'Waar staat jouw ziekenhuis met palliatieve zorg?'",
    "datum": "2026-05-18",
    "einddatum": "2026-06-01",
    "tijd": null,
    "locatie": null,
    "type": "bijeenkomst",
    "beschrijving": "Ben je zorgprofessional in het ziekenhuis en wil je meer inzicht in de sterke punten én verbeterpunten van de palliatieve zorg in jouw organisatie, in vergelijking met het Kwaliteitskader palliatieve zorg Nederland? En ook in hoe je zo’n evaluatie aanpakt en de resultaten vertaalt naar een verbeterplan? Sluit dan aan bij een van de twee digitale inspiratiesessies over de zelfevaluatie palliatieve zorg en leer van de praktijkervaringen van het Zuyderland Medisch Centrum. Deelname is kosteloos. De...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://www.linkedin.com/posts/palliaweb_ben-je-zorgprofessional-in-het-ziekenhuis-activity-7456602780707753984-AQQs?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAP9N9sBdJ8SSmZT990KVtTkDvdBuNGgL5Q",
    "relatie": "niet-direct"
  },
  {
    "id": "FeSf_lruH0GcSBMbKQmc_pgAH06A",
    "titel": "Nationaal congres palliatieve zorg 2026 (voor alle PZ-zorgverleners)",
    "datum": "2026-10-01",
    "einddatum": "2026-10-02",
    "tijd": null,
    "locatie": null,
    "type": "bijeenkomst",
    "beschrijving": "Nationaal Congres Palliatieve Zorg 2026 1 en 2 oktober 2026, Congrescentrum Papendal in Arnhem Dit jaar vindt op 1 en 2 oktober het Nationaal Congres Palliatieve Zorg plaats met het thema 'De kunst van palliatieve zorg'. De programmacommissie van het NCPZ stelt een programma samen over de gehele breedte van de palliatieve zorg.Programma Het thema van het Nationaal Congres Palliatieve Zorg (NCPZ) dit jaar is 'de kunst van palliatieve zorg'. Al meer dan 30 jaar bouwen we in Nederland samen aan de...",
    "doelgroep": null,
    "actielijn": "Algemeen",
    "url": "https://www.zonmw.nl/nl/agenda/nationaal-congres-palliatieve-zorg-2026",
    "relatie": "niet-direct"
  },
  {
    "id": "XVRErd81lUCUIAptM5A_jpgAJCgn",
    "titel": "NPPZ II Congres Palliatieve zorg: Next Level",
    "datum": "2026-09-30",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "bijeenkomst",
    "beschrijving": "De afgelopen jaren hebben we samen grote stappen gezet om de palliatieve zorg verder te ontwikkelen en te verankeren in de reguliere zorg en onderwijs. Tijdens het congres blikken we kort terug op behaalde successen, delen we inspirerende praktijkvoorbeelden en denken we samen na over de toekomst van de palliatieve zorg voor iedereen (kinderen, jongeren, volwassenen ongeacht hun ziekte of leeftijd). 🎯 Wat kun je verwachten? ✔ Inspirerende dag vol nieuwe inzichten ✔ Ruimte om te netwerken met ge...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://nppz.org/nppz-ii-congres-2026/",
    "relatie": "niet-direct"
  },
  {
    "id": "3lWvexZJckCozGWoJH1QWZgAIQvU",
    "titel": "Webinar digitale gegevens uitwisseling PZNL",
    "datum": "2026-06-08",
    "einddatum": null,
    "tijd": "13:00 - 15:00",
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Uitnodiging webinar Digitale ondersteuning proactieve zorgplanning Ben je benieuwd hoe digitale ondersteuning kan bijdragen aan proactieve zorgplanning, netwerkzorg en betere samenwerking in de keten? Wil je weten hoe je als zorgverlener digitale informatie over behandelwensen en -grenzen gebruikt die in een eerder stadium door zorgverleners uit andere domeinen zijn vastgelegd, ook in spoedsituaties? Of ben je benieuwd hoe je nu al relevante stappen kunt zetten, wanneer de digitalisering van net...",
    "doelgroep": null,
    "actielijn": "Digitale ondersteuning",
    "url": null,
    "relatie": "direct"
  },
  {
    "id": "uBBn6pYHeUCSqCnefIgVSZgAAJdK",
    "titel": "hartfalen en praten over morgen (voor verpleegkundigen en verpleegkundig specialisten)",
    "datum": "2026-06-01",
    "einddatum": null,
    "tijd": null,
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Werk jij als verpleegkundige of verpleegkundig specialist met hartfalenpatiënten en hun naasten? Meld je dan kosteloos aan voor het online webinar ‘Hartfalen en praten over morgen’. In 90 minuten krijg je praktische handvatten voor proactieve zorgplanning, symptoomverlichting en samenwerking in de keten, zodat je patiënten met hartfalen en hun naasten tijdig en passend kunt ondersteunen. Praktische info: · Datum: maandag 1 juni 2026 · Tijd: 16.00 tot 17.30 uur · Locatie: online · Deelname is kos...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://www.linkedin.com/company/palliaweb/posts/?feedView=all",
    "relatie": "direct"
  },
  {
    "id": "FvXJzq-R_kKI__P-ZhZFiJgAKUL_",
    "titel": "inspiratiebijeenkomst over het Utrechts Symptoom Dagboek (voor elke professional die meer wil weten over de USD-4D)",
    "datum": "2026-07-02",
    "einddatum": "2026-07-02",
    "tijd": "19:00 - 20:30",
    "locatie": "",
    "type": "bijeenkomst",
    "beschrijving": "Wat je kunt verwachten In de laatste levensfase is de vraag ‘Hoe gaat het?’ vaak lastig te beantwoorden. Het Utrechts Symptoom Dagboek vier dimensioneel (USD-4D) helpt erbij om in gesprek een duidelijk beeld te krijgen van hoe het met iemand gaat en wat belangrijk is. De vier dimensies van palliatieve zorg staan hierin centraal. Doelen van de bijeenkomst zijn: Hoe helpt werken met het USD jou bij het verlenen van passende zorg met behoud van eigen regie? Zicht krijgen op de vraag of en hoe je me...",
    "doelgroep": "",
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://palliaweb.nl/netwerk-eemland/agenda/inspiratiebijeenkomst-over-het-utrechts-symptoomda",
    "relatie": "niet-direct"
  },
  {
    "id": "IDA3XsCF0U-LvW2yiKVbfZgAG6TK",
    "titel": "webinar ‘Herkennen en erkennen van de palliatieve fase’ (voor alle zorgverleners)",
    "datum": "2026-06-23",
    "einddatum": null,
    "tijd": "15:30 - 17:00",
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Veel mensen in de palliatieve fase geven aan dat gesprekken over wensen, behoeften en kwaliteit van leven vaak pas laat op gang komen. Terwijl juist tijdige herkenning van de palliatieve fase kan helpen om eerder passende ondersteuning en zorg te bieden. Hoe herken je de palliatieve fase op tijd? En hoe ga je vervolgens het gesprek aan over wensen, waarden en grenzen van zorg? Tijdens het webinar ‘Herkennen en erkennen van de palliatieve fase’ krijg je praktische handvatten en tools om palliatie...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://lnkd.in/e5YUCuww",
    "relatie": "direct"
  },
  {
    "id": "nx1Py61qIkKs_ADo9lP2epgADePr",
    "titel": "Inspiratiesessie Gedragsverandering - Van inhoud naar gedrag: wat werkt echt? (voor o.a. transformatie-aanjagers)",
    "datum": "2026-06-25",
    "einddatum": null,
    "tijd": "15:30 - 17:00",
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Uit de mail van NPPZII: Graag nodigen we jullie hierbij uit voor de online inhoudelijke bijeenkomst van het NPPZII Leerwerkplatform: Gedragsverandering 'Van inhoud naar gedrag: wat werkt echt?' op 25 juni 2026. Hoe zorg je dat goede ideeën in de praktijk ook écht worden toegepast? Tijdens deze inspiratiesessie ontdek je hoe gedrag en cultuur bepalend zijn voor succesvolle verandering. Drs. Rona van der Dussen neemt je mee in de psychologie achter gedragsverandering en vertaalt theorie naar concr...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": null,
    "relatie": "direct"
  },
  {
    "id": "Tbhoq9DcGkSfsF_Bvt5X-5gADfDR",
    "titel": "Online sessie Proactieve Zorgplanning (PZP) in het ziekenhuis",
    "datum": "2026-06-23",
    "einddatum": null,
    "tijd": "16:00 - 17:30",
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "VOORAANKONDIGING Online sessie Proactieve Zorgplanning (PZP) in het ziekenhuis 23 juni 2026 – 16.00-17.30 uur Hoe krijg je jouw ziekenhuis in beweging rondom Proactieve Zorgplanning? Op dinsdag 23 juni 2026 organiseren we de tweede inspirerende en interactieve sessie voor projectleiders en kartrekkers die werken aan de implementatie van PZP binnen hun ziekenhuis. In 90 minuten gaan we met elkaar in gesprek over hoe proactieve zorgplanning verder te brengen in het ziekenhuis, en praten we door ov...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://teams.microsoft.com/meet/323931540751306?p=sayI2HnqmBNm6levw5",
    "relatie": "direct"
  },
  {
    "id": "q-4RQ_d0J0uRQREVCG-XCpgAHBjn",
    "titel": "Palliatieve zorg binnen de Islam - Tot de laatste adem en daarna",
    "datum": "2026-06-25",
    "einddatum": null,
    "tijd": null,
    "locatie": null,
    "type": "bijeenkomst",
    "beschrijving": "Palliatieve zorg binnen de Islam in beeld gebracht Hoe ga je binnen de Islamitische zorg om met sterven en overlijden? Hoe zien de rituelen eruit? En waarom is het belangrijk? Vanuit de gids ‘Tot de laatste adem en daarna’ van Samira El Moussaoui brengen we dit thema tot leven. Na een inleiding van Samira, volgt een theaterstuk gespeeld door zorgprofessionals. Daarna gaan we in gesprek met een panel van huisarts, politicus en een familielid om te bespreken waarom dit zo belangrijk is voor de zor...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://palindestad.nl/utrecht/agenda/tot-de-laatste-adem-en-daarna/",
    "relatie": "niet-direct"
  },
  {
    "id": "8_kiAe2TLUK4dapHmW--pJgAHnKt",
    "titel": "Scholing Spreken over sterven en dood - Existentiële zorg in de palliatieve fase",
    "datum": "2026-09-16",
    "einddatum": null,
    "tijd": "19:15 - 20:30",
    "locatie": null,
    "type": "bijeenkomst",
    "beschrijving": "Scholing Spreken over sterven en dood - Existentiële zorg in de palliatieve fase Datum16-09-2026 Tijd19.15-20.30 uur (inloop vanaf 19.00 u) LocatieDe Pol Nijkerk, Vetkamp 85, zaal Diamant DoelgroepVerpleegkundigen, verzorgenden en vrijwilligers regio Eemland + NW Veluwe KostenKosteloos SPREKEN OVER STERVEN EN DOOD Existentiële zorg in de palliatieve fase In je werk heb je contact met mensen in de laatste fase van hun leven. Je wilt er voor hen zijn en hen ondersteunen. Daarbij kom je vragen tege...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://palliaweb.nl/netwerk-eemland/agenda/scholing-spreken-over-sterven-en-dood-existentiele",
    "relatie": "niet-direct"
  },
  {
    "id": "Gxze0rBs5UO6ulsTS4X4GpgADDcb",
    "titel": "Webinar Beter Laten Beter Doen palliatieve zorg (UNO Amsterdam)",
    "datum": "2026-06-24",
    "einddatum": null,
    "tijd": "14:00 - 15:00",
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Doelgroep: Verpleegkundigen, verzorgenden, kwaliteitsverpleegkundigen en andere zorgprofessionals werkzaam in het verpleeghuis. Datum: woensdag 24 juni Tijd: 14.00-15.00 Passende palliatieve zorg in het verpleeghuis vraagt om bewuste keuzes van verpleging en verzorging: wat draagt nog bij aan kwaliteit van leven en welzijn van bewoners, en welke handelingen kunnen beter worden afgebouwd of achterwege gelaten? In dit webinar nemen we je mee in een actueel onderzoeksproject naar het beter doen én...",
    "doelgroep": null,
    "actielijn": "Deskundigheidsbevordering",
    "url": null,
    "relatie": "niet-direct"
  },
  {
    "id": "93TkjqTxKEGIVjlV6HkBXpgABvJo",
    "titel": "Voorstelling en themamiddag 'Wat als de dood het leven is?' (voor patiënten/naasten en zorgverleners)",
    "datum": "2026-07-11",
    "einddatum": null,
    "tijd": "",
    "locatie": "ZIMIHC theater Stefanus, Utrecht",
    "type": "bijeenkomst",
    "beschrijving": "Componist en musicus Hermine Schneider - zelf ongeneeslijk ziek - speelt op 11 juli haar indrukwekkende voorstelling 'Wat als de dood het leven is?' met een ensemble (strijkers, contrabas, marimba, trompet/bugel) en actrice Imme Steinmann. De voorstelling vormt het hart van een themamiddag over palliatieve zorg. Naast de voorstelling zijn er informatiestands, groepsgesprekken en wordt het publiek uitgenodigd bij te dragen aan een groeiend wandkleed. Organisatie: Stichting CineMusica en ZIMIHC theater Stefanus, ondersteund door Netwerken Palliatieve Zorg Utrecht en PAL in de Stad Utrecht.",
    "doelgroep": "",
    "actielijn": "Maatschappelijke bewustwording",
    "url": "https://www.zimihc.nl/agenda/wat-als-de-dood-het-leven-is/",
    "relatie": "direct"
  },
  {
    "id": "week-palliatieve-zorg-2026",
    "titel": "Week van de Palliatieve Zorg 2026",
    "datum": "2026-10-03",
    "einddatum": "2026-10-10",
    "tijd": "",
    "locatie": "",
    "type": "campagne",
    "beschrijving": "Jaarlijkse week met aandacht voor palliatieve zorg in Nederland.",
    "doelgroep": "",
    "actielijn": "Maatschappelijke bewustwording",
    "url": null,
    "relatie": "direct"
  },
  {
    "id": "1782220646127",
    "titel": "Het Jaarcongres Palliatieve Zorg",
    "datum": "2026-09-08",
    "einddatum": null,
    "tijd": "9.30-16.45",
    "locatie": "Ede",
    "type": "bijeenkomst",
    "beschrijving": "Op het Jaarcongres Palliatieve Zorg 2026 oefen je met de dilemma's die je dagelijks raken en krijg je praktische handvatten om zelfverzekerder, zorgvuldiger en menselijker te handelen.\n\nAan de hand van herkenbare praktijkcasuïstiek uit verpleeghuis, thuiszorg en hospice werk je aan vragen zoals:\n\nHoe voer je een eerlijk gesprek over euthanasie en palliatieve sedatie?\nHoe leg je palliatieve sedatie helder uit aan patiënt én familie?\nHoe ga je om met botsende wensen van naasten?\nHoe werk je samen met huisarts en wijkteam als visies verschillen?\nHoe blijf je nabij zonder jezelf te verliezen?\nHoe ga je om met rouw, morele stress en cultuurverschillen?",
    "doelgroep": "Voor alle zorgprofessionals die werkzaam zijn in de palliatieve zorg, zoals verpleegkundigen, gespecialiseerd verpleegkundigen, geestelijk verzorgers, praktijkondersteuners, praktijkverpleegkundigen, verpleegkundigen in de wijk en verzorgenden IG.",
    "actielijn": "Deskundigheidsbevordering",
    "url": "https://congressen.nursing.nl/event/jaarcongres-palliatieve-zorg/?utm_medium=email&utm_source=Nursing_Aanmelding%20(AAN)_PalliatieveZorg_nj_2026_AvW_X-EM1_gesprekken_clicks-vorige-selecties&utm_campaign=Events_2026_Nursing&tid=TIDP4864282X711E890F4A5D4735BDF9076E96713EC4YI4",
    "relatie": "niet-direct"
  },
  {
    "id": "1782220997383",
    "titel": "Palliatief Kennisfestival",
    "datum": "2026-09-29",
    "einddatum": null,
    "tijd": "13.00 – 17.00",
    "locatie": "Zwolle",
    "type": "bijeenkomst",
    "beschrijving": "Het Palliatief Kennisfestival is geen congres als vele andere, maar een inspirerend festival over palliatieve zorg waarin de mens in de palliatieve fase centraal staat. Met korte sessies, interactieve workshops, theater, muziek en ruimte voor echte ontmoeting. Voor iedereen die betrokken is bij palliatieve zorg. In de praktijk, het onderwijs, onderzoek of daarbuiten en die wil verdiepen, verbinden en vernieuwen.\n\n* Accreditatie wordt aangevraagd\n** Toegangsprijs: 10 euro voor studenten, 27,50 euro voor professionals inclusief een horeca tegoed waarmee je wat kunt eten en drinken.",
    "doelgroep": "Voor iedereen die werkzaam is in de PZ",
    "actielijn": "Maatschappelijke bewustwording",
    "url": "https://palliatiefkennisfestival.nl/",
    "relatie": "direct"
  },
  {
  "id": "netwerkbijeenkomst-utrecht-20260922",
    "titel": "Netwerkbijeenkomst 'Met elkaar samenwerken én vernieuwen' - NPZ Utrecht stad en Zuidoost-Utrecht",
    "datum": "2026-09-22",
    "einddatum": null,
    "tijd": "12:00 - 15:00",
    "locatie": "Van der Valk Hotel, De Holle Bilt 1, De Bilt",
    "type": "bijeenkomst",
    "beschrijving": "Netwerkevent gericht op ontmoeting, kennisdeling en samenwerking: terugblik op netwerkontwikkelingen, gesprekken met transformatieaanjagers over kansen en uitdagingen in palliatieve zorg, werkgroepen over samenwerking, en een sessie over inclusieve zorg met islamitische perspectieven op leven en dood. Inclusief lunch. Kosteloos. Aanmelden verplicht vóór 31 augustus 2026 via netwerkpalliatievezorgutrecht@outlook.com (naam, functie, organisatie vermelden).",
    "doelgroep": "Medewerkers van partnerorganisaties van het Netwerk Palliatieve Zorg Utrecht Stad en Zuidoost-Utrecht",
    "actielijn": "Afspraken en samenwerking",
    "url": "https://palliaweb.nl/netwerk-utrechtstadenzuidoost/agenda/netwerkbijeenkomst",
    "relatie": "direct"
  },
  {
    "id": "webinar-digitale-nalatenschap-20261008",
    "titel": "Webinar: Regel je digitale nalatenschap",
    "datum": "2026-10-08",
    "einddatum": null,
    "tijd": "19:00 - 20:15",
    "locatie": "Online",
    "type": "bijeenkomst",
    "beschrijving": "Praktisch webinar met concrete handvatten om je digitale nalatenschap goed te regelen en inzicht in wat er na een overlijden geregeld moet worden. Aan bod komen concrete voorbeelden, praktische tips en duidelijke acties. Na afloop weet je wat onder digitale nalatenschap valt, kun je jouw accounts en digitale bezittingen in kaart brengen, weet je welke informatie en wensen je kunt vastleggen voor nabestaanden en welke stappen nabestaanden kunnen zetten om digitale accounts, abonnementen en gegevens af te handelen. Docent: Erik de Bruin, vrijwilliger van Bibliotheek Eemland en ambassadeur van Seniorweb. Aanmelden kan t/m 6 oktober 2026.",
    "doelgroep": "Algemeen publiek",
    "actielijn": "Maatschappelijke bewustwording",
    "url": "https://palliaweb.nl/netwerk-eemland/agenda/webinar-regel-je-digitale-nalatenschap",
    "relatie": null,
    "contactpersoon": "Willemien.schep@beweging3.nl"
  }
];
